### PR TITLE
New Strategy options

### PR DESCRIPTION
**Pull request by mattbrun**
This pull request should increase the compatibility of the Strategy with different LDAP servers (i.e.: Windows Active Directory, OpenLDAP on Linux/Sun Solaris).
- Options added to Strategy creation:
  - authOnly: if true only the bind against the LDAP is done, otherwise also the search will be executed.
  - authMode: 0 for the Windows AD user definition (user name only), 1 for the OpenLDAP user definition (complete DN: user id + base DN).
  - uidTag: string representing the user id tag in the complete DN used as a user with authMode 1.
  - debug: if set to true, debug informations are printed to cmd (very usefull when interfacing new LDAP servers ;) ).
- Modified the code for Strategy accordingly to the added options.
- When defining a filter for the search, if the string '$uid$' is used inside the filter string, it will be replaced by the user id given for the authentication - i.e. we can use as a filter '(uid=$uid$)', which for instance will be translated in '(uid=user1)'.
- Added command line examples to access win\* and *nix LDAP servers.

Regards,
Matteo

### CODE REVIEW

**Comment by mintbridge** [comment]
Wow Thanks, i've only had a quick look through it and it looks good but I will go through it in more detail over the weekend.

**Comment by mattbrun** [comment]
Ok, thanks! :)
I'm available for any question!

**Comment by nathasm** [comment]
I actually just used this with success. I did have to make a couple of tweaks but I think that was specific to my LDAP instance. I'll comment the code to discuss my changes

**Comment by mattbrun** [comment]
@nathasm thx for the hints. i'll give them a try tomorrow and then write back to you if they work for me, so that we may have a common solution :)

**Comment by mattbrun** [comment]
I'll deploy and test Solaris on monday, so I suggest to wait until then to merge the pull request if accepted.

**Comment by tedyoung** [comment]
Any idea when these changes will be merged in?

**Comment by mattbrun** [comment]
sorry guys,
i hadn't the time to check the changes proposed by @nathasm, but till now i used my branch in production without problems. i guess it may be merged without problems for now.

**Comment by mintbridge** [comment]
@mattbrun no problem, ill get it tested and merged over the weekend

**Comment by mattbrun** [comment]
@mintbridge appreciated :)

**Pull request merged**
